'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Analytics

    '''<summary>
    '''ctl00 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctl00 As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''dsCustomerCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCustomerCountry As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''chProdCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chProdCategories As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''dsProductsCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsProductsCategories As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblResidence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResidence As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProdCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProdCategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Chart1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Chart1 As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''dsProductsN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsProductsN As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Chart2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Chart2 As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''dsLoginActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsLoginActive As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblMostPurchProd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMostPurchProd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActive As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInactive As Global.System.Web.UI.WebControls.Label
End Class
